name: mla_202411
channels:
  - conda-forge
dependencies:
  - python==3.11.10
  - altair
  - autopep8
  - beautifulsoup4
  - black
  - bokeh
  - bottleneck
  - crepes
  - cx_oracle
  - cython
  - dask
  - dataframe_image
  - datarobot
  - dtreeviz
  - evidently
  - explainerdashboard
  - fastapi
  - fastparquet
  - fastprogress
  - flask
  - gif
  - gitpython
  - graphviz
  - h5py
  - hiplot
  - html5lib
  - hypothesis
  - imbalanced-learn
  - joblib
  - jpype1
  - jupyter
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - jupyterlab
  - lightgbm
  - line_profiler
  - loguru
  - lxml
  - mapie
  - matplotlib
  - matplotlib-venn
  - memory_profiler
  - missingno
  - mlflow
  - nannyml
  - nbdime
  - networkx
  - ngboost
  - nose
  - numba
  - numexpr
  - numpy
  - openpyxl
  - optuna
  - pandas
  - pandera
  - papermill
  - pathtools
  - patool
  - pillow
  - plotly
  - polars
  - psutil
  - pydot
  - pygmo
  - pygraphviz
  - pynomaly
  - pyod
  - pyodbc
  - pypdf
  - pytest
  - python-graphviz
  - regex
  - rise
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - shap
  - sqlalchemy
  - statsmodels
  - streamlit
  - sweetviz
  - tqdm
  - tsfresh
  - unidecode
  - watermark
  - xgboost
  - xlrd
  - xlsxwriter
  - xlwt
  - xmltodict
  - yapf
  - ydata-profiling